spring:
  jackson:
    default-property-inclusion: non-null
  datasource:
    url: jdbc:mysql://pagination1.cbkeomiao1ip.us-east-1.rds.amazonaws.com/pagination
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
